#.travis.yml

language: node_js
node_js:
  - "8"
sudo: required
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 
addons:
    chrome: stable
branches:
  only:
    - master

script:
  - ng lint

  - ng build --aot --prod
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app:
    master: customercomment

notifications:
  email:
    on_failure: change
    on_success: change