#.travis.yml

language: node_js
node_js:
  - "8"
dist: trusty

branches:
  only:
    - master
addons:
  chrome: stable

script:
  - ng build --prod
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app:
    master: customercomment

notifications:
  email:
    on_failure: change
    on_success: change