#.travis.yml

language: node_js
node_js:
  - "8"
addons:
  chrome: beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

script:
  - ng lint
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  - ng build --aot --prod
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app:
    master: customercomment

notifications:
  email:
    on_failure: change
    on_success: change